name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! You can ping either Neil Shah or Sbelka and we will take a look.'
        pr-message: 'Thanks for contributing to MyCoin! If all checks are good, then one of our project admins will take a look and either merge, or request changes.'
